/** EUobserver Think Tank — Google Apps Script backend */
const TT={TZ:'Europe/Brussels',S:{settings:'Settings',questions:'Questions',participants:'Participants',responses:'Responses',results:'Results'},TERMS:['SCHUMAN','BERLAYMONT','TRILOGUE','COREPER','JOURDAN','LEOPOLD','SPAAK','EUROPA','CHARLEMAGNE','HEMICYCLE','ACQUIS','RAPPORTEUR','COMITOLOGY','COHESION','CABINET','ATTACHE','COUNCIL','COMMISSION','PARLIAMENT','STRASBOURG','LUXEMBOURG','CINQUANTENAIRE','JUSTUS','LIPSIUS']};

function onOpen(){SpreadsheetApp.getUi().createMenu('Think Tank').addItem('Set up / repair sheets','setupThinkTank').addItem('Add tomorrow’s question row','addTomorrowQuestion').addItem('Refresh quiz links','refreshQuestionLinks').addItem('Refresh results dashboard','refreshResults').addToUi();}

function setupThinkTank(){const ss=SpreadsheetApp.getActive();ensure_(ss,TT.S.settings,['key','value']);ensure_(ss,TT.S.questions,['day','question','option_a','option_b','status','source_url','editor_note','quiz_url']);ensure_(ss,TT.S.participants,['code','created_at']);ensure_(ss,TT.S.responses,['key','submitted_at','day','code','prediction_a_pct','vote']);ensure_(ss,TT.S.results,['day','question','responses','option_a_pct','mean_prediction_a','median_prediction_a','mean_abs_error','quiz_url','last_refreshed']);const settings=ss.getSheetByName(TT.S.settings);upsert_(settings,'SITE_URL','https://hackejandro.github.io/eu-media-poll/');upsert_(settings,'MIN_RANK_SAMPLE','10');const q=ss.getSheetByName(TT.S.questions);if(q.getLastRow()===1){const t=shift_(today_(),1);q.getRange(2,1,3,8).setValues([[t,'Will the EU have more than 30 member states by 2035?','Yes','No','DRAFT','','Sample — replace before publishing',''],[shift_(t,1),'Should the EU issue common debt to finance defence?','Yes','No','DRAFT','','Sample — replace before publishing',''],[shift_(t,2),'Will cash still be commonly used in the EU in 2040?','Yes','No','DRAFT','','Sample — replace before publishing','']]);}refreshQuestionLinks();format_();SpreadsheetApp.getUi().alert('Think Tank is ready. Edit Questions, set status to PUBLISHED, then deploy this script as a Web App.');}

function addTomorrowQuestion(){const q=sheet_(TT.S.questions),day=shift_(today_(),1);if(findQuestion_(day))return SpreadsheetApp.getUi().alert('A row for tomorrow already exists.');q.appendRow([day,'','Yes','No','DRAFT','','',quizUrl_(day)]);q.activate();q.setActiveSelection(`B${q.getLastRow()}`);}
function refreshQuestionLinks(){const q=sheet_(TT.S.questions);if(q.getLastRow()<2)return;const vals=q.getRange(2,1,q.getLastRow()-1,1).getValues();q.getRange(2,8,vals.length,1).setValues(vals.map(r=>[r[0]?quizUrl_(normaliseDay_(r[0])):'']));}

function doGet(e){try{const p=(e&&e.parameter)||{},a=String(p.action||'health');let d;if(a==='health')d={ok:true,service:'EUobserver Think Tank',today:today_()};else if(a==='newCode')d=newCode_();else if(a==='validateCode')d=validate_(p.code);else if(a==='question')d=question_(p.day);else if(a==='status')d=status_(p.day,p.code);else if(a==='summary')d=summary_(p.day,p.code);else d={ok:false,error:'Unknown action'};return output_(d,p.callback);}catch(err){return output_({ok:false,error:String(err&&err.message||err)},e&&e.parameter&&e.parameter.callback);}}
function doPost(e){try{const p=(e&&e.parameter)||{},d=String(p.action||'')==='answer'?saveAnswer_(p):{ok:false,error:'Unknown action'};return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON);}catch(err){return ContentService.createTextOutput(JSON.stringify({ok:false,error:String(err&&err.message||err)})).setMimeType(ContentService.MimeType.JSON);}}

function newCode_(){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const sh=sheet_(TT.S.participants);for(let i=0;i<40;i++){const term=TT.TERMS[Math.floor(Math.random()*TT.TERMS.length)],code=`${term}-${String(Math.floor(Math.random()*100000)).padStart(5,'0')}`;if(!participantExists_(code)){sh.appendRow([code,new Date()]);return{ok:true,code};}}throw new Error('Could not allocate a Brussels code.');}finally{lock.releaseLock();}}
function validate_(raw){const code=cleanCode_(raw);return{ok:true,valid:!!code&&participantExists_(code)};}

function question_(rawDay){const day=cleanDay_(rawDay||today_());if(day>today_())return{ok:true,state:'future',day};const q=findQuestion_(day);if(!q||q.status.toUpperCase()!=='PUBLISHED')return{ok:true,state:'missing',day};return{ok:true,state:day===today_()?'open':'closed',day,question:q.question,option_a:q.option_a,option_b:q.option_b};}
function status_(rawDay,rawCode){const day=cleanDay_(rawDay),code=cleanCode_(rawCode);if(!day||!code)return{ok:false,error:'Missing day or code'};const r=findResponse_(day,code);return r?{ok:true,answered:true,prediction:Number(r.prediction),vote:r.vote}:{ok:true,answered:false};}
function saveAnswer_(p){const day=cleanDay_(p.day),code=cleanCode_(p.code),prediction=Number(p.prediction),vote=String(p.vote||'').toUpperCase();if(day!==today_())return{ok:false,error:'Answers are only accepted for today’s question.'};const q=findQuestion_(day);if(!q||q.status.toUpperCase()!=='PUBLISHED')return{ok:false,error:'Question is not open.'};if(!participantExists_(code))return{ok:false,error:'Unknown Brussels code.'};if(!Number.isFinite(prediction)||prediction<0||prediction>100||!['A','B'].includes(vote))return{ok:false,error:'Invalid answer.'};const lock=LockService.getScriptLock();lock.waitLock(10000);try{const existing=findResponse_(day,code);if(existing)return{ok:true,answered:true,duplicate:true,prediction:Number(existing.prediction),vote:existing.vote};sheet_(TT.S.responses).appendRow([`${day}|${code}`,new Date(),day,code,Math.round(prediction),vote]);return{ok:true,answered:true,prediction:Math.round(prediction),vote};}finally{lock.releaseLock();}}

function summary_(rawDay,rawCode){const day=cleanDay_(rawDay);if(day>=today_())return{ok:true,state:day>today_()?'future':'open',day};const q=findQuestion_(day);if(!q||q.status.toUpperCase()!=='PUBLISHED')return{ok:true,state:'missing',day};const rows=responseRows_(day),n=rows.length;if(!n)return{ok:true,state:'closed',day,question:q.question,option_a:q.option_a,option_b:q.option_b,responses:0,option_a_pct:0,mean_prediction_a:null,user:null};const actual=rows.filter(r=>r.vote==='A').length/n*100,preds=rows.map(r=>Number(r.prediction)),mean=preds.reduce((a,b)=>a+b,0)/n;let user=null;const code=cleanCode_(rawCode);if(code){const own=rows.find(r=>r.code===code);if(own){const error=Math.abs(Number(own.prediction)-actual),min=Number(setting_('MIN_RANK_SAMPLE')||10);let beat=null;if(n>=min){const errors=rows.map(r=>Math.abs(Number(r.prediction)-actual)),worse=errors.filter(x=>x>error).length;beat=worse/n*100;}user={prediction:Number(own.prediction),vote:own.vote,error,beat_pct:beat};}}return{ok:true,state:'closed',day,question:q.question,option_a:q.option_a,option_b:q.option_b,responses:n,option_a_pct:actual,mean_prediction_a:mean,user};}

function refreshResults(){const out=sheet_(TT.S.results),q=sheet_(TT.S.questions),rows=q.getLastRow()>1?q.getRange(2,1,q.getLastRow()-1,8).getValues():[],res=[];rows.forEach(r=>{const day=r[0]?normaliseDay_(r[0]):'';if(!day||String(r[4]).toUpperCase()!=='PUBLISHED')return;const rr=responseRows_(day);if(!rr.length){res.push([day,r[1],0,'','','','',quizUrl_(day),new Date()]);return;}const n=rr.length,actual=rr.filter(x=>x.vote==='A').length/n*100,p=rr.map(x=>Number(x.prediction)).sort((a,b)=>a-b),mean=p.reduce((a,b)=>a+b,0)/n,median=n%2?p[(n-1)/2]:(p[n/2-1]+p[n/2])/2,mae=p.reduce((s,x)=>s+Math.abs(x-actual),0)/n;res.push([day,r[1],n,actual,mean,median,mae,quizUrl_(day),new Date()]);});out.clearContents();out.getRange(1,1,1,9).setValues([['day','question','responses','option_a_pct','mean_prediction_a','median_prediction_a','mean_abs_error','quiz_url','last_refreshed']]);if(res.length)out.getRange(2,1,res.length,9).setValues(res);format_();}

function responseRows_(day){const sh=sheet_(TT.S.responses);if(sh.getLastRow()<2)return[];return sh.getRange(2,1,sh.getLastRow()-1,6).getValues().filter(r=>String(r[2])===day).map(r=>({key:r[0],submitted:r[1],day:String(r[2]),code:String(r[3]),prediction:Number(r[4]),vote:String(r[5])}));}
function findResponse_(day,code){const sh=sheet_(TT.S.responses);if(sh.getLastRow()<2)return null;const hit=sh.getRange(2,1,sh.getLastRow()-1,1).createTextFinder(`${day}|${code}`).matchEntireCell(true).findNext();if(!hit)return null;const r=sh.getRange(hit.getRow(),1,1,6).getValues()[0];return{key:r[0],submitted:r[1],day:String(r[2]),code:String(r[3]),prediction:Number(r[4]),vote:String(r[5])};}
function participantExists_(code){if(!code)return false;const sh=sheet_(TT.S.participants);if(sh.getLastRow()<2)return false;return!!sh.getRange(2,1,sh.getLastRow()-1,1).createTextFinder(code).matchEntireCell(true).findNext();}
function findQuestion_(day){const sh=sheet_(TT.S.questions);if(sh.getLastRow()<2)return null;const v=sh.getRange(2,1,sh.getLastRow()-1,8).getValues();for(let i=0;i<v.length;i++){const r=v[i];if(r[0]&&normaliseDay_(r[0])===day)return{row:i+2,day,question:String(r[1]),option_a:String(r[2]),option_b:String(r[3]),status:String(r[4]),source_url:String(r[5]),editor_note:String(r[6]),quiz_url:String(r[7])};}return null;}

function ensure_(ss,name,headers){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);return sh;}
function format_(){const ss=SpreadsheetApp.getActive();Object.values(TT.S).forEach(name=>{const sh=ss.getSheetByName(name);if(!sh)return;sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).setFontWeight('bold').setBackground('#000020').setFontColor('#ffffff');sh.autoResizeColumns(1,Math.max(1,sh.getLastColumn()));});const q=ss.getSheetByName(TT.S.questions);if(q){q.setColumnWidth(2,420);q.setColumnWidth(7,260);q.setColumnWidth(8,320);}}
function upsert_(sh,key,value){const rows=sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1,2).getValues():[],idx=rows.findIndex(r=>String(r[0])===key);if(idx>=0)sh.getRange(idx+2,2).setValue(value);else sh.appendRow([key,value]);}
function setting_(key){const sh=sheet_(TT.S.settings);if(sh.getLastRow()<2)return'';const hit=sh.getRange(2,1,sh.getLastRow()-1,2).getValues().find(r=>String(r[0])===key);return hit?String(hit[1]):'';}
function quizUrl_(day){let base=setting_('SITE_URL')||'https://hackejandro.github.io/eu-media-poll/';if(!base.endsWith('/'))base+='/';return`${base}?day=${encodeURIComponent(day)}`;}
function sheet_(name){const sh=SpreadsheetApp.getActive().getSheetByName(name);if(!sh)throw new Error(`Missing sheet: ${name}. Run setupThinkTank().`);return sh;}
function today_(){return Utilities.formatDate(new Date(),TT.TZ,'yyyy-MM-dd');}
function shift_(day,offset){const p=String(day).split('-').map(Number),d=new Date(Date.UTC(p[0],p[1]-1,p[2]+offset,12));return Utilities.formatDate(d,'UTC','yyyy-MM-dd');}
function normaliseDay_(v){if(Object.prototype.toString.call(v)==='[object Date]')return Utilities.formatDate(v,TT.TZ,'yyyy-MM-dd');return cleanDay_(v);}
function cleanDay_(v){const s=String(v||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw new Error('Invalid day.');return s;}
function cleanCode_(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9-]/g,'').slice(0,40);}
function output_(data,callback){const cb=String(callback||'').replace(/[^A-Za-z0-9_$\.]/g,''),payload=JSON.stringify(data);if(cb)return ContentService.createTextOutput(`${cb}(${payload});`).setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(payload).setMimeType(ContentService.MimeType.JSON);}
